### ISSUE TITLE
Actualizar el diagrama funcional

### ISSUE THREAD

**Issue by pokengineer** [ada-lovelace-progra/AsistenteDeCocina#1]
lo dejo como issue para no olvidarnos, pero falta actualizar el [diagrama funcional](https://github.com/ada-lovelace-progra/LaCosaDeSoa/blob/master/Sistema-Embebido/Diagramas/Funcional.png) al proyecto de asistente de cocina

**Comment by seback95** [comment]
subiiiii iiishuuuuu
